<a href="https://colab.research.google.com/github/NatumanyaDuncan/assignment_repo/blob/main/Project3_part_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = "/content/drive/MyDrive/queries/title-akas-us-only.csv"
df = pd.read_csv(data)
df

<ipython-input-1-035a672294e5>:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data)

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
0,tt0000001,6,Carmencita,US,\N,imdbDisplay,\N,0
1,tt0000002,7,The Clown and His Dogs,US,\N,\N,literal English title,0
2,tt0000005,10,Blacksmith Scene,US,\N,imdbDisplay,\N,0
3,tt0000005,1,Blacksmithing Scene,US,\N,alternative,\N,0
4,tt0000005,6,Blacksmith Scene #1,US,\N,alternative,\N,0
...,...,...,...,...,...,...,...,...
1452559,tt9916560,1,March of Dimes Presents: Once Upon a Dime,US,\N,imdbDisplay,\N,0
1452560,tt9916620,1,The Copeland Case,US,\N,imdbDisplay,\N,0
1452561,tt9916702,1,Loving London: The Playground,US,\N,\N,\N,0
1452562,tt9916756,1,Pretty Pretty Black Girl,US,\N,imdbDisplay,\N,0
1452563,tt9916764,1,38,US,\N,imdbDisplay,\N,0

In [ ]:
# Step 1: Movies released in the United States
df = df[df['region'] == 'US']

# Step 2: Movies released between 2000 and 2021 (inclusive)
df = df[(df['titleId'].str.startswith('tt2')) | (df['titleId'].str.startswith('tt1'))]

# Step 3: Include only full-length movies
df = df[df['types'] == 'movie']

# Step 4: Exclude movies with missing values for genre or runtime
df = df.dropna(subset=['title', 'region', 'types'])

# Step 5: Include only fictional movies (exclude Documentary genre)
df = df[~df['types'].str.contains('Documentary')]

In [ ]:
# Display summary information
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   titleId          0 non-null      object
 1   ordering         0 non-null      int64
 2   title            0 non-null      object
 3   region           0 non-null      object
 4   language         0 non-null      object
 5   types            0 non-null      object
 6   attributes       0 non-null      object
 7   isOriginalTitle  0 non-null      object
dtypes: int64(1), object(7)
memory usage: 0.0+ bytes